service: teacher-assistant
frameworkVersion: "3"
provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 1024
  timeout: 30
  environment:
    STAGE: ${self:provider.stage}
    REGION_AWS: ${self:provider.region}
    LOG_LEVEL: INFO
    FUNCTION_TIMEOUT: ${self:provider.timeout}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - bedrock:InvokeModel
            - bedrock:InvokeModelWithResponseStream
          Resource: "arn:aws:bedrock:*:*:foundation-model/*"
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "arn:aws:logs:*:*:*"
plugins:
  - serverless-dotenv-plugin
  - serverless-python-requirements #this is needed for local development
  - serverless-offline #this is needed for local development
custom:
  dotenv:
    path: .env
package:
  individually: true
  include:
    - handlers/**
  exclude:
    - "**/__pycache__/**"
    - "**/*.pyc"
    - "**/.DS_Store"
    - "**/.venv/**"
    - "**/venv/**"
    - "**/node_modules/**"
    - "**/.pytest_cache/**"
    - "**/.git/**"
    - "**/.idea/**"
    - "**/tests/**"
    - "**/*.log"
    - "**/*.md"
    - "**/README*"
functions:
  teacher:
    handler: handlers.teacher_handler.lambda_handler
    name: ${self:service}-${self:provider.stage}-teacher
    description: Main teacher orchestrator function
    timeout: 30
    events:
      - http:
          path: ask
          method: post
          cors: true
    environment:
      FUNCTION_NAME: teacher
resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}-${self:provider.stage}-api
        Description: Teacher Assistant API Gateway
  Outputs:
    ApiGatewayRestApiId:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: ${self:service}-${self:provider.stage}-api-id
    ApiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - ApiGatewayRestApi
          - RootResourceId
      Export:
        Name: ${self:service}-${self:provider.stage}-api-root-resource-id
